Vagrant.configure("2") do |config|

	vagrant_version = Vagrant::VERSION.sub(/^v/, '')
	if vagrant_version < "1.3.0"
		abort(sprintf("You need to have at least v1.3.0 of vagrant installed. You are currently using v%s", vagrant_version));
	end
    
    #------------------------------------------------------------------------------------
    # rabbitmq broker
    #------------------------------------------------------------------------------------
    config.vm.define "rabbitmq" do |rabbitmq|

        rabbitmq.vm.box = "hashicorp/precise64"

        rabbitmq.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", 1024]
        end

        rabbitmq.vm.network "forwarded_port", guest: 15672, host: 45672
        rabbitmq.vm.network "forwarded_port", guest: 5672, host: 35672
        rabbitmq.vm.network "private_network", ip: "10.0.115.2"

        rabbitmq.vm.provision :shell do |shell|
            shell.inline = "mkdir -p /etc/puppet/modules;
                            puppet module install puppetlabs-rabbitmq;"
        end

        rabbitmq.vm.provision :puppet do |puppet|
            puppet.manifests_path = "puppet"
            puppet.manifest_file  = "default.pp"
            puppet.options = "--verbose --debug"
        end
    end
	
end